config/routes.rb
Rails.application.routes.draw do
  resources :pools do
    get :instance_config
    get :close_pool
    get :open_pool
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pools#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pool.rb
class Pool < ApplicationRecord

  def create_piri!
    require 'docker'
    self.port = new_piri_port
    self.pool_url = "#{ROOT_URL}:#{port}"
    pp "Creating piri container for #{title} with port: #{port}"

    container = Docker::Container.create(
        'Image' => 'chrisss404/piri:latest',
        'ExposedPorts' => { '8080/tcp' => {} },
        'HostConfig' => {
          'PortBindings' => {
            '8080/tcp' => [{ 'HostPort' => port}]
          }
        }
      )
    self.container_id = container.id

    container.start
    self.save!
  end

  def create_ui!
    require 'docker'
    self.ui_port = new_ui_port
    pp "Creating ui container for #{title} with port: #{ui_port}"

    container = Docker::Container.create(
        'Image' => 'registry.gitlab.com/huhn/piri-web:latest',
        #'Image' => 'piri-web:latest',
        'Env'=> ["TITLE='#{title}'", "LOGO_URL='#{logo_url}'", "POOL_URL='#{pool_url}'"],
        'ExposedPorts' => { '3000/tcp' => {} },
        'HostConfig' => {
          'PortBindings' => {
            '3000/tcp' => [{ 'HostPort' => ui_port}]
          }
        }
      )
    self.container_ui_id = container.id

    pp 'cotainter'
    pp container.to_s
    pp "container.json"
    pp container.json["Config"]["Env"]
    container.start
    self.save!
  end

  def stop_piri!
    container = Docker::Container.get(container_id)
    container.stop
    self.pool_url = nil
    self.container_id = nil
    save!
  end

  def new_piri_port

    # use port 30001-39999 TODO: Fix if we go big ;)
    # we start with 1 to match with ids
    return "30#{(Pool.all.count + 1).to_s.rjust(3, '0')}"

  end

  def new_ui_port

    # use port 30001-39999 TODO: Fix if we go big ;)
    # we start with 1 to match with ids
    return "40#{(Pool.all.count + 1).to_s.rjust(3, '0')}"

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools
  # GET /pools.json
  def index
    @pools = Pool.all
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = Pool.new(pool_params)

    respond_to do |format|
      if @pool.save
        if(params[:hosting][:pool] == "1")
          @pool.create_piri!
        end
        format.html { redirect_to @pool, notice: 'Pool was successfully created.' }
        format.json { render :show, status: :created, location: @pool }
      else
        format.html { render :new }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @pool }
      else
        format.html { render :edit }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_url, notice: 'Pool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def instance_config
    @pool = Pool.find(params[:pool_id])
    pp @pool
  end

  def close_pool
    @pool = Pool.find(params[:pool_id])
    @pool.stop_piri!
    redirect_to @pool
  end
  def open_pool
    @pool = Pool.find(params[:pool_id])
    @pool.create_piri!
    redirect_to @pool
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:title, :pool_url, :logo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoolParty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
     <script src="https://cdn.rawgit.com/santiagohecar/flights-map/master/dist/flights-map.min.js"></script>

  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pools/_form.html.erb
<%= form_with(model: pool, local: true) do |form| %>
  <% if pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
      <% pool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <p>You have your own pool? Add your pool url here:</p>
  <div class="form-group">
    <%= form.label :pool_url %>
    <%= form.text_field :pool_url, class: 'form-control' %>
  </div>


  <p>You don't have your own pool? Click here to create on</p>

  <div class="form-group">
    <%= check_box(:hosting, "pool", {}) %>
  </div>

  <div class="form-group">
    <%= form.label :logo_url %>
    <%= form.text_field :logo_url, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/pools/edit.html.erb
<h1>Editing Pool</h1>

<%= link_to 'Back', pools_path %> | 
<%= link_to 'Edit', edit_pool_path(@pool) %>

<%= render 'form', pool: @pool %>

app/views/pools/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">Pool party!</h1>
  <p class="lead">This is a collection of piri pools. You can also add your remote pool or create a new pool.</p>
  <hr class="my-4">
  <p>Learn more about piri.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="https://ecosystem.iota.org/projects/piri" role="button" target="_blank">Learn more</a>
  </p>
</div>
<%= link_to 'New Pool', new_pool_path %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Pool url</th>
      <th>port</th>
      <th>container id</th>
      <th>link to pool</th>
      <th>link to pool ui</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pools.each do |pool| %>
      <tr>
        <td><%= pool.title %></td>
        <td><%= pool.pool_url %></td>
        <td><%= pool.port %></td>
        <td><%= pool.container_id&.truncate(12) %></td>
        <td>
          <%= link_to "visit Pool", "#{request.protocol + request.host}:#{pool.port}", target: "_blank" if !pool.pool_url %>
          <%= link_to "visit Pool", "#{pool.pool_url}", target: "_blank" if pool.pool_url %>
        </td>
        <td><%= link_to "visit UI", "#{request.protocol + request.host}:#{pool.ui_port}", target: "_blank" %></td>
        <td><%= link_to 'Manage', pool %></td>
        <td><%= link_to 'Edit', edit_pool_path(pool) %></td>
        <td><%= link_to 'Destroy', pool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3>(TODO) Pool Party Map</h3>
<p>All pools and their nodes in different colors. Draw the IoT World with colors! ;) </p>
<div id="schedules_map"></div>

 <div style="width:800px;">
   <a id="reset" href="javascript:void(0)">Reset</a>
   <a id="zoom_in" href="javascript:void(0)">Zoom in</a>
   <a id="zoom_out" href="javascript:void(0)">Zoom out</a>
   <a id="show_schedules"  href="javascript:void(0)">all</a>
   <div id="station_name" ></div>
 </div>
 <script type="text/javascript">


$(document).ready(function()
   {
     var map = new FlightsMap("schedules_map",
     {
       width: 960,
       height: 440,
       stations: "https://raw.githubusercontent.com/santiagohecar/flights-map/master/example/stations.json",
       flights: "https://raw.githubusercontent.com/santiagohecar/flights-map/master/example/flights.json"
     });

     $("#reset").click(function() { map.reset(); });
     $("#zoom_in").click(function() { map.zoomIn(); });
     $("#zoom_out").click(function() { map.zoomOut(); });
     $("#show_schedules").click(function() { map.showSchedules(); });
   });

</script>

app/views/pools/new.html.erb
<h1>New Pool</h1>

<%= render 'form', pool: @pool %>

<%= link_to 'Back', pools_path %>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Manage pool</h1>

<%= link_to 'Back', pools_path %> | 
<%= link_to 'Edit', edit_pool_path(@pool) %>

<div class="card">
  <div class="card-body">
    <%= image_tag @pool.logo_url, style: 'height: 200px' %>
    <h5 class="card-title"><%= @pool.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= link_to(@pool.pool_url, @pool.pool_url,  target: '_blank') if  @pool.pool_url %></h6>
    <p class="card-text">Pool description</p>
    <%= button_to "close pool", pool_close_pool_url(@pool), class: 'card-link btn btn-danger', method: :get if @pool.container_id %>
    <%= button_to "open pool", pool_open_pool_url(@pool), class: 'card-link btn btn-success', method: :get if !@pool.container_id && !@pool.pool_url %>
  </div>
</div>
<br>
<br>
<br>
<br>
<h3>Pool Map</h3>
<p>This is a demo, which could show pool nodes and their connection to each other</p>
<div id="schedules_map"></div>

 <div style="width:800px;">
   <a id="reset" href="javascript:void(0)">Reset</a>
   <a id="zoom_in" href="javascript:void(0)">Zoom in</a>
   <a id="zoom_out" href="javascript:void(0)">Zoom out</a>
   <a id="show_schedules"  href="javascript:void(0)">all</a>
   <div id="station_name" ></div>
 </div>
 <script type="text/javascript">


$(document).ready(function()
   {
     var map = new FlightsMap("schedules_map",
     {
       width: 960,
       height: 440,
       stations: "https://raw.githubusercontent.com/santiagohecar/flights-map/master/example/stations.json",
       flights: "https://raw.githubusercontent.com/santiagohecar/flights-map/master/example/flights.json"
     });

     $("#reset").click(function() { map.reset(); });
     $("#zoom_in").click(function() { map.zoomIn(); });
     $("#zoom_out").click(function() { map.zoomOut(); });
     $("#show_schedules").click(function() { map.showSchedules(); });
   });

</script>